<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>orekit_jpype</groupId>
  <artifactId>orekit_jpype</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <orekit.version>13.1.4</orekit.version>
      <rugged.version>4.0</rugged.version>
      <hipparchus.version>4.0.1</hipparchus.version>
  </properties>
  <repositories>
    <repository>
      <id>orekit-releases</id>
      <url>https://packages.orekit.org/repository/maven-releases/</url>
      <releases><enabled>true</enabled></releases>
      <snapshots><enabled>false</enabled></snapshots>
    </repository>
    <repository>
      <id>orekit-snapshots</id>
      <url>https://packages.orekit.org/repository/maven-snapshots/</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>false</enabled></snapshots>
    </repository>
  </repositories>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.6.1</version>
        <configuration>
          <artifactItems>
            <artifactItem>
              <groupId>org.orekit</groupId>
              <artifactId>orekit</artifactId>
              <version>${orekit.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>orekit_jpype/jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.orekit</groupId>
              <artifactId>orekit</artifactId>
              <version>${orekit.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.orekit</groupId>
              <artifactId>rugged</artifactId>
              <version>${rugged.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.orekit</groupId>
              <artifactId>rugged</artifactId>
              <version>${rugged.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-core</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-core</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-filtering</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-filtering</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-fitting</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>orekit_jpype/jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-fitting</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-geometry</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>orekit_jpype/jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-geometry</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-ode</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>orekit_jpype/jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-ode</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-optim</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>orekit_jpype/jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-optim</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-stat</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>orekit_jpype/jars</outputDirectory>
            </artifactItem>
            <artifactItem>
              <groupId>org.hipparchus</groupId>
              <artifactId>hipparchus-stat</artifactId>
              <version>${hipparchus.version}</version>
              <type>jar</type>
              <classifier>javadoc</classifier>
              <overWrite>true</overWrite>
              <outputDirectory>temp_jars</outputDirectory>
            </artifactItem>
          </artifactItems>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <name>orekit_artifacts</name>
</project>