import java.net
import java.util.stream
import typing



class InetAddressResolver:
    def lookupByAddress(self, byteArray: typing.List[int]) -> str: ...
    def lookupByName(self, string: str, lookupPolicy: 'InetAddressResolver.LookupPolicy') -> java.util.stream.Stream[java.net.InetAddress]: ...
    class LookupPolicy:
        IPV4: typing.ClassVar[int] = ...
        IPV6: typing.ClassVar[int] = ...
        IPV4_FIRST: typing.ClassVar[int] = ...
        IPV6_FIRST: typing.ClassVar[int] = ...
        def characteristics(self) -> int: ...
        @staticmethod
        def of(int: int) -> 'InetAddressResolver.LookupPolicy': ...

class InetAddressResolverProvider:
    def get(self, configuration: 'InetAddressResolverProvider.Configuration') -> InetAddressResolver: ...
    def name(self) -> str: ...
    class Configuration:
        def builtinResolver(self) -> InetAddressResolver: ...
        def lookupLocalHostName(self) -> str: ...

class URLStreamHandlerProvider(java.net.URLStreamHandlerFactory): ...


class __module_protocol__(typing.Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("java.net.spi")``.

    InetAddressResolver: typing.Type[InetAddressResolver]
    InetAddressResolverProvider: typing.Type[InetAddressResolverProvider]
    URLStreamHandlerProvider: typing.Type[URLStreamHandlerProvider]
